In [30]:
import numpy as np

In [31]:
demo = [10,20,30]
np.array(demo)

array([10, 20, 30])

In [32]:
#demo2 = [10,20,"30"]
#np.array(demo2)

demo2 = [10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [33]:
np.zeros(5, int)
x1 = np.ones(5)

print(x1)

[1. 1. 1. 1. 1.]


In [34]:
x1[2] = "xyz"

ValueError: could not convert string to float: 'xyz'

In [35]:
x = np.zeros(10)
x.dtype

dtype('float64')

In [36]:
y = np.zeros(10, int)
y.dtype

dtype('int64')

In [37]:
# 2d array
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
x5=np.ones(5)
print(x5)

[1. 1. 1. 1. 1.]


In [39]:
x5[3]=2
print(x5)

[1. 1. 1. 2. 1.]


In [40]:
x5[3]="4"
print(x5)

[1. 1. 1. 4. 1.]


In [41]:
x5[3]="abc"
print(x5)

ValueError: could not convert string to float: 'abc'

In [42]:
# 3d array
arr=np.zeros((3,4,5))
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [43]:
arr[0][1][2]=5
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [44]:
arr[0][1]=6
print(arr)

[[[0. 0. 0. 0. 0.]
  [6. 6. 6. 6. 6.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [45]:
arr[0]=7
print(arr)

[[[7. 7. 7. 7. 7.]
  [7. 7. 7. 7. 7.]
  [7. 7. 7. 7. 7.]
  [7. 7. 7. 7. 7.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [46]:
arr.shape

(3, 4, 5)

In [47]:
arr2=[1,2,3,4,5,6]
print(arr2[2:5])

[3, 4, 5]


In [48]:
print(arr2[:3])

[1, 2, 3]


In [58]:
print(arr2[3:])

[4, 5, 6]


In [57]:
print(arr2[-1])

6


In [73]:
arr3=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr3[1])

[4 5 6]


In [75]:
print(arr3[1:3])

[[4 5 6]
 [7 8 9]]


In [74]:
print(arr3[:,1]) #only one column

[ 2  5  8 11]


In [76]:
print(arr3[2:4,1])

[ 8 11]


In [79]:
print(arr3[1:3,0:2])

[[4 5]
 [7 8]]
