In [18]:
import numpy as np

In [19]:
demo = [10,20,30]
np.array(demo)

array([10, 20, 30])

In [20]:
#demo2 = [10,20,"30"]
#np.array(demo2)

demo2 = [10,20,"xyz"]
np.array(demo2)

array(['10', '20', 'xyz'], dtype='<U21')

In [21]:
np.zeros(5, int)
x1 = np.ones(5)

print(x1)

[1. 1. 1. 1. 1.]


In [22]:
x1[2] = "xyz"

ValueError: could not convert string to float: 'xyz'

In [ ]:
x = np.zeros(10)
x.dtype

In [ ]:
y = np.zeros(10, int)
y.dtype

In [ ]:
# 2d array
np.zeros((3,4))

In [ ]:
x5=np.ones(5)
print(x5)

In [ ]:
x5[3]=2
print(x5)

In [ ]:
x5[3]="4"
print(x5)

In [ ]:
x5[3]="abc"
print(x5)

In [ ]:
# 3d array
arr=np.zeros((3,4,5))
print(arr)

In [23]:
arr[0][1][2]=5
print(arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 5. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]
